- name: Create a subnet
  ec2_vpc_subnet: 
    aws_access_key: "{{ aws_id }} "
    aws_secret_key: "{{ aws_key }}"
    region: "{{ aws_region }}"
    state: present
    cidr: "{{ cidr_ip_subnet }}"
    vpc_id: "{{ ansible_VPC_net.vpc.id }}"
    map_public: yes
    tags: 
      Name: public_subnet
    register: create_VPC_subnet
  
- name: Display the ansibleVPC output
  debug:
    var: create_VPC_subnet
    